spring.application.name=auth-api

# PostgreSQL (rodando na sua máquina Windows)
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/tokenTeste
spring.datasource.username=postgres
spring.datasource.password=2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis (rodando no Docker, serviço chamado "redis")
spring.data.redis.host=redis
spring.data.redis.port=6379

# Expiração do token
token-Expiration=36000